### ISSUE TITLE
Getting class not found errors on upgrading selenium from 3.141.59 to Selenium 4

### ISSUE THREAD

**Issue by chetanvelicheti** [healenium/healenium#1]
Describe the problem
Healenium is giving error when using with Selenium 4 library.

Screenshots
java.lang.NoClassDefFoundError: org/openqa/selenium/internal/WrapsElement
at com.epam.healenium.utils.ProxyFactory.createWebElementProxy(ProxyFactory.java:43)
at com.epam.healenium.handlers.proxy.BaseHandler.wrapElement(BaseHandler.java:119)
at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.lambda$invoke$0(SelfHealingProxyInvocationHandler.java:40)
at java.base/java.util.Optional.map(Optional.java:260)
at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:40)
at jdk.proxy2/jdk.proxy2.$Proxy26.findElement(Unknown Source)
at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:197)
at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:193)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
at util.CommonMethods.waitUntilTime(CommonMethods.java:19)
at pages.LoginPage.enterValueInField(LoginPage.java:25)
at pages.LoginPage.doLogin(LoginPage.java:70)
at parallel.TravelReqSteps.user_successfully_logs_into_j_stack_application_using_and(TravelReqSteps.java:40)
at ✽.User successfully logs into JStack application using "TravelRequest" and 0(file:///C:/Users/tpulluri/eclipse-workspace/JStackProject/src/test/resources/parallel/TravelRequest.feature:5)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.internal.WrapsElement
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
at com.epam.healenium.utils.ProxyFactory.createWebElementProxy(ProxyFactory.java:43)
at com.epam.healenium.handlers.proxy.BaseHandler.wrapElement(BaseHandler.java:119)
at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.lambda$invoke$0(SelfHealingProxyInvocationHandler.java:40)
at java.base/java.util.Optional.map(Optional.java:260)
at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:40)
at jdk.proxy2/jdk.proxy2.$Proxy26.findElement(Unknown Source)
at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:197)
at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:193)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
at util.CommonMethods.waitUntilTime(CommonMethods.java:19)
at pages.LoginPage.enterValueInField(LoginPage.java:25)
at pages.LoginPage.doLogin(LoginPage.java:70)
at parallel.TravelReqSteps.user_successfully_logs_into_j_stack_application_using_and(TravelReqSteps.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
at io.cucumber.java.Invoker.invoke(Invoker.java:24)
at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:92)
at io.cucumber.core.runner.TestStep.run(TestStep.java:64)
at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
at io.cucumber.core.runner.TestCase.run(TestCase.java:104)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:71)
at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:151)
at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:135)
at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at io.cucumber.junit.Cucumber.runChild(Cucumber.java:199)
at io.cucumber.junit.Cucumber.runChild(Cucumber.java:90)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:234)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

Please complete the following information:

Versions of components (web and backend):hlm-backend:3.1.3,web-3.3
Selenium version-4.0.0
Platform (Java, .NET, etc)-Java
Full stacktrace with exception-posted above
Logs from healenium-backend container
WebDriver creation
Additional context
Add any other context about the problem here. For example, using of additional frameworks like Sizzle library, Robot Framework or JDI, etc.-Cucumber ,POM ,Junit  .

It would be of great help if you could help us. @DzmitryHumianiuk @GannaChernyshova @AnatoliZaitsau

**Comment by ElenaStepuro** [comment]
Hello @chetanvelicheti !
Unfortunately, for now healenium not integrated with Selenium 4.0.0. Please, use 3.141.59 version if you can.
We'll notify you when it'll be implemented.

**Comment by chetanvelicheti** [comment]
Thank you @ElenaStepuro . Any approximate release time line would be appreacated. 

Thank and you once again for your time and patience.
