### ISSUE TITLE
[BUG]: unable to run dotnet example tests using selenoid out of the box

### ISSUE THREAD

**Issue by ashishnalagotla71** [healenium/healenium#22]
### Describe the bug

Unable to run dotnet example tests using selenoid out of the box

### How to reproduce the issue

```shell
1)Build the dotnet example after pulling from below repo
https://github.com/healenium/healenium-example-dotnet
2)Run the tests using nunit3 console runner .
```

### Logs appeared during using Healenium

```shell
1) Error : Healenium.Selenium.Tests.CssTest.TestCssAttribute
OpenQA.Selenium.WebDriverException : Unable to parse: You are using Selenoid HEAD!
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, DriverOptions options)
   at Healenium.Selenium.Tests.BaseTest.SetUp() in C:\Users\Hp\healenium-example-dotnet\Healenium.Selenium.Tests\Healenium.Selenium.Tests\BaseTest.cs:line 23
--TearDown
   at Healenium.Selenium.Tests.BaseTest.AfterAll() in C:\Users\Hp\healenium-example-dotnet\Healenium.Selenium.Tests\Healenium.Selenium.Tests\BaseTest.cs:line 46
```

### Expected behavior

Should be able to run the tests

### Actual behavior

Error is thrown while running tests

### Healenium Web version

None

### Healenium Backend version

3.3.4

### Platform

.NET

**Comment by Alex-Reif** [comment]
Hi @ashishnalagotla71 , This error means your docker version no compatible with selenoid version. We recommend to use Healenium with selenium-grid (docker-compose -f docker-compose-selenium-grid.yaml up -d )
