### ISSUE TITLE
[Need support]: in starting the helenium service in our machine I am trying to start the helenium server the with out Docker

### ISSUE THREAD

**Issue by clrameshchandra** [healenium/healenium#29]
### Describe the problem

Need help in starting the helenium service in our machine I am trying to start the helenium server the with out docker Docker version

### Healenium Web version

Java 17

### Healenium Backend version

3.4.1

### Selenium version

Selenium 4.5

### Platform

Python

### Logs appeared during using Healenium

```shell
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: ERROR: no schema has been selected to create in\n   Position: 14 [Failed SQL: (0) CREATE TABLE databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (ID))] 
2023-10-15 17:27:57.466  INFO 864 - [       main] c.z.hikari.HikariDataSource      : HikariPool-1 - Shutdown initiated... 
2023-10-15 17:27:57.487  INFO 864 - [       main] c.z.hikari.HikariDataSource      : HikariPool-1 - Shutdown completed. 
2023-10-15 17:27:57.494  INFO 864 - [       main] o.a.c.core.StandardService       : Stopping service [Tomcat] 
2023-10-15 17:27:57.571  INFO 864 - [       main] nEvaluationReportLoggingListener : \n \n \n \n Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
2023-10-15 17:27:57.618 ERROR 864 - [       main] o.s.boot.SpringApplication       : Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: ERROR: no schema has been selected to create in\n   Position: 14 [Failed SQL: (0) CREATE TABLE databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (ID))]\n \n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)\n \n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)\n \n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)\n \n 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)\n \n 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)\n \n 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)\n \n 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)\n \n 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)\n \n 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)\n \n 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1157)\n \n 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:911)\n \n 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)\n \n 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)\n \n 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)\n \n 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)\n \n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)\n \n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)\n \n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)\n \n 	at com.epam.healenium.Application.main(Application.java:9)\n \n 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n \n 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n \n 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n \n 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)\n \n 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)\n \n 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)\n \n 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)\n \n 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)\n \n Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: ERROR: no schema has been selected to create in\n   Position: 14 [Failed SQL: (0) CREATE TABLE databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (ID))]\n \n 	at liquibase.command.CommandScope.execute(CommandScope.java:236)\n \n 	at liquibase.Liquibase.lambda$update$0(Liquibase.java:223)\n \n 	at liquibase.Scope.lambda$child$0(Scope.java:197)\n \n 	at liquibase.Scope.child(Scope.java:206)\n \n 	at liquibase.Scope.child(Scope.java:196)\n \n 	at liquibase.Scope.child(Scope.java:175)\n \n 	at liquibase.Liquibase.runInScope(Liquibase.java:1361)\n \n 	at liquibase.Liquibase.update(Liquibase.java:215)\n \n 	at liquibase.Liquibase.update(Liquibase.java:197)\n \n 	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:329)\n \n 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:284)\n \n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n \n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n \n 	... 26 common frames omitted\n \n Caused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: ERROR: no schema has been selected to create in\n   Position: 14 [Failed SQL: (0) CREATE TABLE databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (ID))]\n \n 	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:341)\n \n 	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:258)\n \n 	at liquibase.command.core.helpers.LockServiceCommandStep.run(LockServiceCommandStep.java:37)\n \n 	at liquibase.command.CommandScope.execute(CommandScope.java:213)\n \n 	... 38 common frames omitted\n \n Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: ERROR: no schema has been selected to create in\n   Position: 14 [Failed SQL: (0) CREATE TABLE databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (ID))]\n \n 	at liquibase.executor.jvm.ChangelogJdbcMdcListener.execute(ChangelogJdbcMdcListener.java:39)\n \n 	at liquibase.lockservice.StandardLockService.init(StandardLockService.java:121)\n \n 	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:297)\n \n 	... 41 common frames omitted\n \n Caused by: liquibase.exception.DatabaseException: ERROR: no schema has been selected to create in\n   Position: 14 [Failed SQL: (0) CREATE TABLE databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (ID))]\n \n 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)\n \n 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:76)\n \n 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)\n \n 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:144)\n \n 	at liquibase.lockservice.StandardLockService.lambda$init$0(StandardLockService.java:121)\n \n 	at liquibase.executor.jvm.ChangelogJdbcMdcListener.lambda$execute$0(ChangelogJdbcMdcListener.java:33)\n \n 	at liquibase.Scope.lambda$child$0(Scope.java:197)\n \n 	at liquibase.Scope.child(Scope.java:206)\n \n 	at liquibase.Scope.child(Scope.java:196)\n \n 	at liquibase.Scope.child(Scope.java:175)\n \n 	at liquibase.executor.jvm.ChangelogJdbcMdcListener.execute(ChangelogJdbcMdcListener.java:32)\n \n 	... 43 common frames omitted\n \n Caused by: org.postgresql.util.PSQLException: ERROR: no schema has been selected to create in\n   Position: 14\n \n 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)\n \n 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)\n \n 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)\n \n 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)\n \n 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)\n \n 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)\n \n 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)\n \n 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)\n \n 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:292)\n \n 	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)\n \n 	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)\n \n 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:460)\n \n 	... 53 common frames omitted\n \n
```

### Additional context

We dont want to use docker, so i am using the one with no docker.
I am not sure where to check the settings for.  

I have followed the steps mentioned in the link https://healenium.io/docs/download_and_install/hlm_proxy

I have installed the postgres and  I was successfully created the DB healenium, and ran 
CREATE USER healenium_user WITH ENCRYPTED PASSWORD 'YDk2nmNs4s9aCP6K';
GRANT ALL PRIVILEGES ON DATABASE healenium TO healenium_user;
ALTER USER healenium_user WITH SUPERUSER;

But i was not successful in running the command "\c healenium healenium_user;"

But i was successfully able to run the next 2 commands mentioned below
CREATE SCHEMA healenium AUTHORIZATION healenium_user;
GRANT USAGE ON SCHEMA healenium TO healenium_user;

After that i downloaded the selenium standalone server 4.5 and was able to run it .
then i was able to run the below steps 

Install Healenium without Docker

1. Download latest version or clone Healenium repository:
Structure of archive:

/shell-installation/ - directory for install Healenium without docker. It contains /selenium-grid (for Healenium-Proxy) and /web (for Healenium-Web) directories

2. Go to /shell-installation/selenium-grid

3. Download Healenium components. Run download_services.sh
the download was successful but i am not able to start the HLM server.

The log shows the above log and failing. 

I am not sure if am missing any thing.
can you please help me. 

Please let me know what and all setting i need to check.

**Comment by clrameshchandra** [comment]
This issue was fixed after creating the schema in the proper DB. I was missing the step to login to newly created DB hence closing the issue.
