### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by danbao** [healenium/healenium#41]
### Describe the bug

I encountered a `NullPointerException` while using Healenium. The error occurs when trying to invoke the `SelfHealingHandler.quit()` method, as `SessionContext.getSelfHealingHandlerBase()` returns null.

### How to reproduce the issue

```shell
1. Configure Healenium and environment.
2. Run the test script in Webdriver.IO.
3. On test completion, invoke the `quit()` method.
4. Encounter a `NullPointerException`.
```

### Logs appeared during using Healenium

```shell
2024-01-16 05:00:19.797  WARN 1 - [8085-exec-8] healenium                        : Trying to heal...
2024-01-16 05:00:19.808  WARN 1 - [8085-exec-8] healenium                        : New element locator have not been found. There is no reference data to selector in the database.\n Make sure that: \n - There is selector on the page http://healenium:7878/healenium/selectors/ and type: single, if not then you have to run successful tests.\n - Your locator was changed on the page and not in code.
2024-01-16 05:00:19.809 ERROR 1 - [8085-exec-8] healenium                        : [Request Handler] Error during handle Proxy Request. Message: no such element: Unable to locate element: {"method":"xpath","selector":"(//*[@data-test-automation-id='root']//*[@data-test-automation-id='changeCredentialsPopup']//*[@data-test-automation-id='changePin'])[1]"}\n   (Session info: chrome=120.0.6099.109)\n For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\n Build info: version: '4.13.0', revision: 'ba948ece5b*'\n System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.88.1.el7.x86_64', java.version: '17.0.9'\n Driver info: org.openqa.selenium.remote.RemoteWebDriver\n Command: [69da24d544db0fd51169586afb595e75, findElement {using=xpath, value=(//*[@data-test-automation-id='root']//*[@data-test-automation-id='changeCredentialsPopup']//*[@data-test-automation-id='changePin'])[1]}]\n Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 120.0.6099.109, chrome: {chromedriverVersion: 120.0.6099.109 (3419140ab66..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:40149}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: {}, se:bidiEnabled: false, se:cdp: ws://172.24.0.12:4444/sessi..., se:cdpVersion: 120.0.6099.109, se:vnc: ws://172.24.0.12:4444/sessi..., se:vncEnabled: true, se:vncLocalAddress: ws://172.24.0.12:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}\n Session ID: 69da24d544db0fd51169586afb595e75, Exception: {} org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"(//*[@data-test-automation-id='root']//*[@data-test-automation-id='changeCredentialsPopup']//*[@data-test-automation-id='changePin'])[1]"}\n   (Session info: chrome=120.0.6099.109)\n For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\n Build info: version: '4.13.0', revision: 'ba948ece5b*'\n System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.88.1.el7.x86_64', java.version: '17.0.9'\n Driver info: org.openqa.selenium.remote.RemoteWebDriver\n Command: [69da24d544db0fd51169586afb595e75, findElement {using=xpath, value=(//*[@data-test-automation-id='root']//*[@data-test-automation-id='changeCredentialsPopup']//*[@data-test-automation-id='changePin'])[1]}]\n Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 120.0.6099.109, chrome: {chromedriverVersion: 120.0.6099.109 (3419140ab66..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:40149}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: {}, se:bidiEnabled: false, se:cdp: ws://172.24.0.12:4444/sessi..., se:cdpVersion: 120.0.6099.109, se:vnc: ws://172.24.0.12:4444/sessi..., se:vncEnabled: true, se:vncLocalAddress: ws://172.24.0.12:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}\n Session ID: 69da24d544db0fd51169586afb595e75\n 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)\n 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)\n 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)\n 	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)\n 	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)\n 	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)\n 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)\n 	at com.epam.healenium.healenium_proxy.command.HealeniumCommandExecutor.execute(HealeniumCommandExecutor.java:31)\n 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)\n 	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)\n 	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)\n 	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:359)\n 	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)\n 	at com.epam.healenium.processor.FindElementProcessor.execute(FindElementProcessor.java:23)\n 	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:42)\n 	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:63)\n 	at com.epam.healenium.healenium_proxy.request.post.override.HealeniumFindElementPostRequest.findElement(HealeniumFindElementPostRequest.java:48)\n 	at com.epam.healenium.healenium_proxy.request.post.override.HealeniumFindElementPostRequest.execute(HealeniumFindElementPostRequest.java:44)\n 	at com.epam.healenium.healenium_proxy.request.post.HealeniumPostRequest.execute(HealeniumPostRequest.java:46)\n 	at com.epam.healenium.healenium_proxy.handler.HealeniumProxyHttpHandler.handleRequest(HealeniumProxyHttpHandler.java:39)\n 	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:52)\n 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)\n 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)\n 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)\n 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)\n 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)\n 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)\n 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)\n 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)\n 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)\n 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)\n 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)\n 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)\n 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)\n 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)\n at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)\n 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)\n 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)\n 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)\n 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)\n 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n 	at java.base/java.lang.Thread.run(Thread.java:840)\n
2024-01-16 05:00:20.123  WARN 1 - [8085-exec-1] healenium                        : [Proxy] Using default Selenium by URL: http://selenium-hub:4444/wd/hub
2024-01-16 05:00:20.125 ERROR 1 - [8085-exec-1] healenium                        : [Request Handler] Error during handle Proxy Request. Message: Cannot invoke "com.epam.healenium.handlers.SelfHealingHandler.quit()" because the return value of "com.epam.healenium.healenium_proxy.model.SessionContext.getSelfHealingHandlerBase()" is null, Exception: {} java.lang.NullPointerException: Cannot invoke "com.epam.healenium.handlers.SelfHealingHandler.quit()" because the return value of "com.epam.healenium.healenium_proxy.model.SessionContext.getSelfHealingHandlerBase()" is null\n 	at com.epam.healenium.healenium_proxy.request.delete.HealeniumDeleteRequest.execute(HealeniumDeleteRequest.java:44)\n 	at com.epam.healenium.healenium_proxy.handler.HealeniumProxyHttpHandler.handleRequest(HealeniumProxyHttpHandler.java:39)\n 	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:52)\n 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)\n 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)\n 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)\n 	at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:936)\n 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:596)\n 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)\n 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)\n 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)\n 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)\n 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)\n 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)\n 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)\n 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)\n 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)\n 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)\n 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)\n 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)\n 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)\n 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)\n 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n 	at java.base/java.lang.Thread.run(Thread.java:840)\n
```

### Expected behavior

Expected to close and release resources normally after test execution without throwing an exception.

### Actual behavior

10:00:19 AM | warning   | main | [browser-proxy-worker] [logged] 2024-01-16T02:00:19.882Z WARN webdriver: Request failed with status 500 due to Cannot invoke "com.epam.healenium.handlers.SelfHealingHandler.quit()" because the return value of "com.epam.healenium.healenium_proxy.model.SessionContext.getSelfHealingHandlerBase()" is null

10:00:19 AM | warning   | main | [browser-proxy-worker] [logged] 2024-01-16T02:00:19.904Z WARN webdriver: Request failed with status 500 due to Cannot invoke "com.epam.healenium.handlers.SelfHealingHandler.quit()" because the return value of "com.epam.healenium.healenium_proxy.model.SessionContext.getSelfHealingHandlerBase()" is null

10:00:19 AM | warning   | main | [browser-proxy-worker] [logged] 2024-01-16T02:00:19.916Z ERROR webdriver: Request failed with status 500 due to unknown error: Cannot invoke "com.epam.healenium.handlers.SelfHealingHandler.quit()" because the return value of "com.epam.healenium.healenium_proxy.model.SessionContext.getSelfHealingHandlerBase()" is null

10:00:19 AM | error     | worker/hIJnJl3MymeczbcAZiD_F | [logged inside test] Error: Cannot invoke "com.epam.healenium.handlers.SelfHealingHandler.quit()" because the return value of "com.epam.healenium.healenium_proxy.model.SessionContext.getSelfHealingHandlerBase()" is null

### Healenium Web version

HealeniumProxyApplication v1.3.8

### Healenium Backend version

HealeniumProxyApplication v1.3.8

### Selenium version

Selenium Gird 4

### Platform

TestRing base on Webdriver.IO

### Additional context

[testring](https://github.com/ringcentral/testring)

**Comment by danbao** [comment]
Refer to this bug ticket for a similar issue:
https://github.com/healenium/healenium/issues/33

**Comment by sharathhatter1** [comment]
any update on this?
