### ISSUE TITLE
[BUG]: Not able to integrate with Gradle 

### ISSUE THREAD

**Issue by kumaran2024** [healenium/healenium#49]
### Describe the bug

Not able to integrate Healenium with Gradle. I created a setup [hlm-we without docker] with the help [this](https://healenium.io/docs/download_and_install/hlm_web) document and self-healing is not getting integrated with Gradle.

### How to reproduce the issue

```shell
1. Create a new Gradle project and complete all prerequisites. 
2. Make necessary changes as per document [https://healenium.io/docs/download_and_install/hlm_web].
```

### Logs appeared during using Healenium

```shell
java.lang.NoSuchMethodError: 'java.util.function.Supplier org.openqa.selenium.remote.http.HttpResponse.getContent()' 

at com.epam.healenium.client.RestClient.getElements(RestClient.java:141) 

at com.epam.healenium.SelfHealingEngine.loadStoredSelectors(SelfHealingEngine.java:169) 

at com.epam.healenium.SelfHealingDriver.callInitActions(SelfHealingDriver.java:65) 

at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:42)
```

### Expected behavior

Self-healing should get integrate with Gradle 

### Actual behavior

Getting NoSuchMethodError exception 

### Healenium Web version

v3.5.1 

### Healenium Backend version

v3.4.3 

### Selenium version

4.20.0 

### Platform

Java

**Comment by kumaran2024** [comment]
@Alex-Reif 
Could you please look into this?
