### ISSUE TITLE
[Need support]: Selenium Grid with appium relay is showing Could not start a new session. Response code 500. Message: Multiple entries with same key: appium:udid=28061FDH2000VW and appium:udid=28061FDH2000VW 

### ISSUE THREAD

**Issue by krishtoautomate** [healenium/healenium#51]
### Describe the problem

Im using appium connected to selenium Grid as relay. started tests pointing to selenium grid. no error is seen for chrome browsers but errors are seen for tests on appium devices:

Could not start a new session. Response code 500. Message: Multiple entries with same key: appium:udid=28061FDH2000VW and appium:udid=28061FDH2000VW 

### Healenium Web version

3.4.5

### Healenium Backend version

3.4.5

### Platform

Java

### Logs appeared during using Healenium

```shell
Could not start a new session. Response code 500. Message: Multiple entries with same key: appium:udid=28061FDH2000VW and appium:udid=28061FDH2000VW
```

**Comment by krishtoautomate** [comment]
can anyone help here

**Comment by imsarathh** [comment]
seams like you added duplicate  **appium:udid=28061FDH2000VW**

remove duplicate item it will resolve issue

**Comment by krishtoautomate** [comment]
Im not sending any duplicate

**Comment by imsarathh** [comment]
we connect imsarathh in IG

**Comment by imsarathh** [comment]
if possible we connect and fix issue

**Comment by krishtoautomate** [comment]
Do you need any logs or setup info?

**Comment by imsarathh** [comment]
yes please share all versions u using like appium, selenium, and helenium versions and also share me logs of appium

**Comment by ShilpaAPatil2024** [comment]
I am also getting 500 error
Logs:
"C:\Program Files\OpenLogic\jdk-11.0.19.7-hotspot\bin\java.exe" -javaagent:D:\IdealC\lib\idea_rt.jar=64875:D:\IdealC\bin -Dfile.encoding=UTF-8 -classpath D:\Projects_Folder\DemoAPP_mobile\target\test-classes;D:\Projects_Folder\DemoAPP_mobile\target\classes;C:\Users\Shilpapatil\.m2\repository\org\junit\jupiter\junit-jupiter-engine\5.11.3\junit-jupiter-engine-5.11.3.jar;C:\Users\Shilpapatil\.m2\repository\org\junit\platform\junit-platform-engine\1.11.3\junit-platform-engine-1.11.3.jar;C:\Users\Shilpapatil\.m2\repository\org\apiguardian\apiguardian-api\1.1.2\apiguardian-api-1.1.2.jar;C:\Users\Shilpapatil\.m2\repository\org\junit\jupiter\junit-jupiter-api\5.11.3\junit-jupiter-api-5.11.3.jar;C:\Users\Shilpapatil\.m2\repository\org\opentest4j\opentest4j\1.3.0\opentest4j-1.3.0.jar;C:\Users\Shilpapatil\.m2\repository\org\junit\platform\junit-platform-commons\1.11.3\junit-platform-commons-1.11.3.jar;C:\Users\Shilpapatil\.m2\repository\junit\junit\4.13.2\junit-4.13.2.jar;C:\Users\Shilpapatil\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-java\4.11.0\selenium-java-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-api\4.11.0\selenium-api-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-chrome-driver\4.11.0\selenium-chrome-driver-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\com\google\auto\service\auto-service-annotations\1.0.1\auto-service-annotations-1.0.1.jar;C:\Users\Shilpapatil\.m2\repository\com\google\guava\guava\31.1-jre\guava-31.1-jre.jar;C:\Users\Shilpapatil\.m2\repository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\Shilpapatil\.m2\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\Shilpapatil\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\Shilpapatil\.m2\repository\org\checkerframework\checker-qual\3.12.0\checker-qual-3.12.0.jar;C:\Users\Shilpapatil\.m2\repository\com\google\errorprone\error_prone_annotations\2.11.0\error_prone_annotations-2.11.0.jar;C:\Users\Shilpapatil\.m2\repository\com\google\j2objc\j2objc-annotations\1.3\j2objc-annotations-1.3.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-chromium-driver\4.11.0\selenium-chromium-driver-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-json\4.11.0\selenium-json-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-manager\4.11.0\selenium-manager-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-devtools-v113\4.11.0\selenium-devtools-v113-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-devtools-v114\4.11.0\selenium-devtools-v114-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-devtools-v115\4.11.0\selenium-devtools-v115-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-devtools-v85\4.11.0\selenium-devtools-v85-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-edge-driver\4.11.0\selenium-edge-driver-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-firefox-driver\4.11.0\selenium-firefox-driver-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-http\4.11.0\selenium-http-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\dev\failsafe\failsafe\3.3.1\failsafe-3.3.1.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-ie-driver\4.11.0\selenium-ie-driver-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\4.11.0\selenium-remote-driver-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-buffer\4.1.92.Final\netty-buffer-4.1.92.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-codec-http\4.1.92.Final\netty-codec-http-4.1.92.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-codec\4.1.92.Final\netty-codec-4.1.92.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-handler\4.1.92.Final\netty-handler-4.1.92.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-common\4.1.92.Final\netty-common-4.1.92.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-transport-classes-epoll\4.1.92.Final\netty-transport-classes-epoll-4.1.92.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-transport-classes-kqueue\4.1.92.Final\netty-transport-classes-kqueue-4.1.92.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-transport-native-epoll\4.1.92.Final\netty-transport-native-epoll-4.1.92.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-transport-native-kqueue\4.1.92.Final\netty-transport-native-kqueue-4.1.92.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-transport-native-unix-common\4.1.92.Final\netty-transport-native-unix-common-4.1.92.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-transport\4.1.92.Final\netty-transport-4.1.92.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-resolver\4.1.92.Final\netty-resolver-4.1.92.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-api\1.26.0\opentelemetry-api-1.26.0.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-context\1.26.0\opentelemetry-context-1.26.0.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-exporter-logging\1.26.0\opentelemetry-exporter-logging-1.26.0.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-sdk-metrics\1.26.0\opentelemetry-sdk-metrics-1.26.0.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-extension-incubator\1.26.0-alpha\opentelemetry-extension-incubator-1.26.0-alpha.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-sdk-logs\1.26.0-alpha\opentelemetry-sdk-logs-1.26.0-alpha.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-api-logs\1.26.0-alpha\opentelemetry-api-logs-1.26.0-alpha.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-api-events\1.26.0-alpha\opentelemetry-api-events-1.26.0-alpha.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-sdk-common\1.26.0\opentelemetry-sdk-common-1.26.0.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-sdk-extension-autoconfigure-spi\1.26.0\opentelemetry-sdk-extension-autoconfigure-spi-1.26.0.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-sdk-extension-autoconfigure\1.26.0-alpha\opentelemetry-sdk-extension-autoconfigure-1.26.0-alpha.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-sdk-trace\1.26.0\opentelemetry-sdk-trace-1.26.0.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-sdk\1.26.0\opentelemetry-sdk-1.26.0.jar;C:\Users\Shilpapatil\.m2\repository\io\opentelemetry\opentelemetry-semconv\1.26.0-alpha\opentelemetry-semconv-1.26.0-alpha.jar;C:\Users\Shilpapatil\.m2\repository\net\bytebuddy\byte-buddy\1.14.4\byte-buddy-1.14.4.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\Shilpapatil\.m2\repository\org\asynchttpclient\async-http-client\2.12.3\async-http-client-2.12.3.jar;C:\Users\Shilpapatil\.m2\repository\org\asynchttpclient\async-http-client-netty-utils\2.12.3\async-http-client-netty-utils-2.12.3.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-codec-socks\4.1.60.Final\netty-codec-socks-4.1.60.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-handler-proxy\4.1.60.Final\netty-handler-proxy-4.1.60.Final.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-transport-native-epoll\4.1.60.Final\netty-transport-native-epoll-4.1.60.Final-linux-x86_64.jar;C:\Users\Shilpapatil\.m2\repository\io\netty\netty-transport-native-kqueue\4.1.60.Final\netty-transport-native-kqueue-4.1.60.Final-osx-x86_64.jar;C:\Users\Shilpapatil\.m2\repository\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar;C:\Users\Shilpapatil\.m2\repository\com\typesafe\netty\netty-reactive-streams\2.0.4\netty-reactive-streams-2.0.4.jar;C:\Users\Shilpapatil\.m2\repository\com\sun\activation\jakarta.activation\1.2.2\jakarta.activation-1.2.2.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-safari-driver\4.11.0\selenium-safari-driver-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\seleniumhq\selenium\selenium-support\4.11.0\selenium-support-4.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\testng\testng\7.9.0\testng-7.9.0.jar;C:\Users\Shilpapatil\.m2\repository\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;C:\Users\Shilpapatil\.m2\repository\com\beust\jcommander\1.82\jcommander-1.82.jar;C:\Users\Shilpapatil\.m2\repository\org\webjars\jquery\3.7.1\jquery-3.7.1.jar;C:\Users\Shilpapatil\.m2\repository\io\appium\java-client\8.5.1\java-client-8.5.1.jar;C:\Users\Shilpapatil\.m2\repository\com\google\code\gson\gson\2.10.1\gson-2.10.1.jar;C:\Users\Shilpapatil\.m2\repository\commons-validator\commons-validator\1.7\commons-validator-1.7.jar;C:\Users\Shilpapatil\.m2\repository\commons-beanutils\commons-beanutils\1.9.4\commons-beanutils-1.9.4.jar;C:\Users\Shilpapatil\.m2\repository\commons-digester\commons-digester\2.1\commons-digester-2.1.jar;C:\Users\Shilpapatil\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\Shilpapatil\.m2\repository\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;C:\Users\Shilpapatil\.m2\repository\com\googlecode\json-simple\json-simple\1.1.1\json-simple-1.1.1.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\cucumber-core\7.15.0\cucumber-core-7.15.0.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\cucumber-gherkin\7.15.0\cucumber-gherkin-7.15.0.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\cucumber-gherkin-messages\7.15.0\cucumber-gherkin-messages-7.15.0.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\messages\22.0.0\messages-22.0.0.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\tag-expressions\6.0.0\tag-expressions-6.0.0.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\cucumber-expressions\17.0.1\cucumber-expressions-17.0.1.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\datatable\7.15.0\datatable-7.15.0.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\cucumber-plugin\7.15.0\cucumber-plugin-7.15.0.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\docstring\7.15.0\docstring-7.15.0.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\html-formatter\20.4.0\html-formatter-20.4.0.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\junit-xml-formatter\0.2.0\junit-xml-formatter-0.2.0.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\ci-environment\10.0.0\ci-environment-10.0.0.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\cucumber-java\7.15.0\cucumber-java-7.15.0.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\cucumber-testng\7.15.0\cucumber-testng-7.15.0.jar;C:\Users\Shilpapatil\.m2\repository\io\cucumber\gherkin\28.0.0\gherkin-28.0.0.jar;C:\Users\Shilpapatil\.m2\repository\commons-io\commons-io\2.16.1\commons-io-2.16.1.jar;C:\Users\Shilpapatil\.m2\repository\com\epam\healenium\healenium-appium\1.3.0\healenium-appium-1.3.0.jar;C:\Users\Shilpapatil\.m2\repository\com\epam\healenium\healenium-web\3.3.0\healenium-web-3.3.0.jar;C:\Users\Shilpapatil\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.13.2.1\jackson-databind-2.13.2.1.jar;C:\Users\Shilpapatil\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.13.2\jackson-annotations-2.13.2.jar;C:\Users\Shilpapatil\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.13.2\jackson-core-2.13.2.jar;C:\Users\Shilpapatil\.m2\repository\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;C:\Users\Shilpapatil\.m2\repository\org\jetbrains\annotations\23.0.0\annotations-23.0.0.jar;C:\Users\Shilpapatil\.m2\repository\one\util\streamex\0.8.1\streamex-0.8.1.jar;C:\Users\Shilpapatil\.m2\repository\org\eclipse\jetty\jetty-server\10.0.10\jetty-server-10.0.10.jar;C:\Users\Shilpapatil\.m2\repository\org\eclipse\jetty\toolchain\jetty-servlet-api\4.0.6\jetty-servlet-api-4.0.6.jar;C:\Users\Shilpapatil\.m2\repository\org\eclipse\jetty\jetty-http\10.0.10\jetty-http-10.0.10.jar;C:\Users\Shilpapatil\.m2\repository\org\eclipse\jetty\jetty-util\10.0.10\jetty-util-10.0.10.jar;C:\Users\Shilpapatil\.m2\repository\org\eclipse\jetty\jetty-io\10.0.10\jetty-io-10.0.10.jar;C:\Users\Shilpapatil\.m2\repository\com\codeborne\selenide\6.1.1\selenide-6.1.1.jar;C:\Users\Shilpapatil\.m2\repository\com\codeborne\selenide-core\6.1.1\selenide-core-6.1.1.jar;C:\Users\Shilpapatil\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\commons\commons-compress\1.21\commons-compress-1.21.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\httpcomponents\client5\httpclient5\5.1.2\httpclient5-5.1.2.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\httpcomponents\core5\httpcore5\5.1.2\httpcore5-5.1.2.jar;C:\Users\Shilpapatil\.m2\repository\org\testcontainers\junit-jupiter\1.16.3\junit-jupiter-1.16.3.jar;C:\Users\Shilpapatil\.m2\repository\org\testcontainers\testcontainers\1.16.3\testcontainers-1.16.3.jar;C:\Users\Shilpapatil\.m2\repository\org\rnorth\duct-tape\duct-tape\1.0.8\duct-tape-1.0.8.jar;C:\Users\Shilpapatil\.m2\repository\com\github\docker-java\docker-java-api\3.2.12\docker-java-api-3.2.12.jar;C:\Users\Shilpapatil\.m2\repository\com\github\docker-java\docker-java-transport-zerodep\3.2.12\docker-java-transport-zerodep-3.2.12.jar;C:\Users\Shilpapatil\.m2\repository\io\github\bonigarcia\webdrivermanager\5.1.0\webdrivermanager-5.1.0.jar;C:\Users\Shilpapatil\.m2\repository\com\github\docker-java\docker-java\3.2.13\docker-java-3.2.13.jar;C:\Users\Shilpapatil\.m2\repository\com\github\docker-java\docker-java-core\3.2.13\docker-java-core-3.2.13.jar;C:\Users\Shilpapatil\.m2\repository\org\bouncycastle\bcpkix-jdk15on\1.64\bcpkix-jdk15on-1.64.jar;C:\Users\Shilpapatil\.m2\repository\org\bouncycastle\bcprov-jdk15on\1.64\bcprov-jdk15on-1.64.jar;C:\Users\Shilpapatil\.m2\repository\org\slf4j\jcl-over-slf4j\1.7.30\jcl-over-slf4j-1.7.30.jar;C:\Users\Shilpapatil\.m2\repository\com\github\docker-java\docker-java-transport-httpclient5\3.2.13\docker-java-transport-httpclient5-3.2.13.jar;C:\Users\Shilpapatil\.m2\repository\com\github\docker-java\docker-java-transport\3.2.13\docker-java-transport-3.2.13.jar;C:\Users\Shilpapatil\.m2\repository\net\java\dev\jna\jna\5.8.0\jna-5.8.0.jar;C:\Users\Shilpapatil\.m2\repository\org\brotli\dec\0.1.2\dec-0.1.2.jar;C:\Users\Shilpapatil\.m2\repository\com\squareup\okhttp3\okhttp\4.9.3\okhttp-4.9.3.jar;C:\Users\Shilpapatil\.m2\repository\com\squareup\okio\okio\2.8.0\okio-2.8.0.jar;C:\Users\Shilpapatil\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.4.0\kotlin-stdlib-common-1.4.0.jar;C:\Users\Shilpapatil\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib\1.4.10\kotlin-stdlib-1.4.10.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\plugins\maven-surefire-plugin\3.0.0-M5\maven-surefire-plugin-3.0.0-M5.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\surefire\maven-surefire-common\3.0.0-M5\maven-surefire-common-3.0.0-M5.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\surefire\surefire-api\3.0.0-M5\surefire-api-3.0.0-M5.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\surefire\surefire-logger-api\3.0.0-M5\surefire-logger-api-3.0.0-M5.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\surefire\surefire-extensions-api\3.0.0-M5\surefire-extensions-api-3.0.0-M5.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\surefire\surefire-booter\3.0.0-M5\surefire-booter-3.0.0-M5.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\surefire\surefire-extensions-spi\3.0.0-M5\surefire-extensions-spi-3.0.0-M5.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\maven-toolchain\3.0-alpha-2\maven-toolchain-3.0-alpha-2.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\shared\maven-artifact-transfer\0.11.0\maven-artifact-transfer-0.11.0.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\shared\maven-common-artifact-filters\3.0.1\maven-common-artifact-filters-3.0.1.jar;C:\Users\Shilpapatil\.m2\repository\org\sonatype\sisu\sisu-inject-plexus\1.4.2\sisu-inject-plexus-1.4.2.jar;C:\Users\Shilpapatil\.m2\repository\org\sonatype\sisu\sisu-inject-bean\1.4.2\sisu-inject-bean-1.4.2.jar;C:\Users\Shilpapatil\.m2\repository\org\sonatype\sisu\sisu-guice\2.1.7\sisu-guice-2.1.7-noaop.jar;C:\Users\Shilpapatil\.m2\repository\org\codehaus\plexus\plexus-java\1.0.5\plexus-java-1.0.5.jar;C:\Users\Shilpapatil\.m2\repository\org\ow2\asm\asm\7.2\asm-7.2.jar;C:\Users\Shilpapatil\.m2\repository\com\thoughtworks\qdox\qdox\2.0-M9\qdox-2.0-M9.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\surefire\surefire-shared-utils\3.0.0-M4\surefire-shared-utils-3.0.0-M4.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\maven-artifact\2.0.11\maven-artifact-2.0.11.jar;C:\Users\Shilpapatil\.m2\repository\org\codehaus\plexus\plexus-utils\1.5.6\plexus-utils-1.5.6.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\maven-compat\3.8.1\maven-compat-3.8.1.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\maven-model\3.8.1\maven-model-3.8.1.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\maven-model-builder\3.8.1\maven-model-builder-3.8.1.jar;C:\Users\Shilpapatil\.m2\repository\javax\inject\javax.inject\1\javax.inject-1.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\maven-builder-support\3.8.1\maven-builder-support-3.8.1.jar;C:\Users\Shilpapatil\.m2\repository\org\eclipse\sisu\org.eclipse.sisu.inject\0.3.4\org.eclipse.sisu.inject-0.3.4.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\maven-settings\3.8.1\maven-settings-3.8.1.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\maven-settings-builder\3.8.1\maven-settings-builder-3.8.1.jar;C:\Users\Shilpapatil\.m2\repository\org\sonatype\plexus\plexus-sec-dispatcher\1.4\plexus-sec-dispatcher-1.4.jar;C:\Users\Shilpapatil\.m2\repository\org\sonatype\plexus\plexus-cipher\1.4\plexus-cipher-1.4.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\maven-core\3.8.1\maven-core-3.8.1.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\resolver\maven-resolver-spi\1.6.2\maven-resolver-spi-1.6.2.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\shared\maven-shared-utils\3.2.1\maven-shared-utils-3.2.1.jar;C:\Users\Shilpapatil\.m2\repository\com\google\inject\guice\4.2.1\guice-4.2.1-no_aop.jar;C:\Users\Shilpapatil\.m2\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\maven-resolver-provider\3.8.1\maven-resolver-provider-3.8.1.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\maven-repository-metadata\3.8.1\maven-repository-metadata-3.8.1.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\resolver\maven-resolver-api\1.6.2\maven-resolver-api-1.6.2.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\resolver\maven-resolver-util\1.6.2\maven-resolver-util-1.6.2.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\resolver\maven-resolver-impl\1.6.2\maven-resolver-impl-1.6.2.jar;C:\Users\Shilpapatil\.m2\repository\org\codehaus\plexus\plexus-interpolation\1.25\plexus-interpolation-1.25.jar;C:\Users\Shilpapatil\.m2\repository\org\eclipse\sisu\org.eclipse.sisu.plexus\0.3.4\org.eclipse.sisu.plexus-0.3.4.jar;C:\Users\Shilpapatil\.m2\repository\javax\enterprise\cdi-api\1.0\cdi-api-1.0.jar;C:\Users\Shilpapatil\.m2\repository\javax\annotation\jsr250-api\1.0\jsr250-api-1.0.jar;C:\Users\Shilpapatil\.m2\repository\org\codehaus\plexus\plexus-component-annotations\2.1.0\plexus-component-annotations-2.1.0.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\wagon\wagon-provider-api\3.4.3\wagon-provider-api-3.4.3.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\maven\maven-plugin-api\3.8.1\maven-plugin-api-3.8.1.jar;C:\Users\Shilpapatil\.m2\repository\org\codehaus\plexus\plexus-classworlds\2.6.0\plexus-classworlds-2.6.0.jar;C:\Users\Shilpapatil\.m2\repository\com\typesafe\config\1.3.4\config-1.3.4.jar;C:\Users\Shilpapatil\.m2\repository\com\epam\healenium\tree-comparing\0.4.10\tree-comparing-0.4.10.jar;C:\Users\Shilpapatil\.m2\repository\org\jsoup\jsoup\1.11.3\jsoup-1.11.3.jar;C:\Users\Shilpapatil\.m2\repository\org\apache\commons\commons-text\1.6\commons-text-1.6.jar;C:\Users\Shilpapatil\.m2\repository\org\slf4j\slf4j-simple\1.7.30\slf4j-simple-1.7.30.jar;C:\Users\Shilpapatil\.m2\repository\org\mapstruct\mapstruct\1.4.2.Final\mapstruct-1.4.2.Final.jar;C:\Users\Shilpapatil\.m2\repository\org\projectlombok\lombok\1.18.20\lombok-1.18.20.jar;C:\Users\Shilpapatil\.m2\repository\org\mapstruct\mapstruct-processor\1.4.2.Final\mapstruct-processor-1.4.2.Final.jar;C:\Users\Shilpapatil\.m2\repository\org\javassist\javassist\3.26.0-GA\javassist-3.26.0-GA.jar org.PageObjects.WebTestSelfHealing.AmazonTest
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'SHILPAPATIL', ip: '192.168.32.1'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:536)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:274)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:159)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
	at org.PageObjects.WebTestSelfHealing.AmazonTest.main(AmazonTest.java:28)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.19'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:137)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:182)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	... 5 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:133)
	... 9 more
Caused by: java.io.UncheckedIOException: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
	at io.appium.java_client.AppiumUserAgentFilter.lambda$apply$0(AppiumUserAgentFilter.java:88)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:48)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:96)
	at io.appium.java_client.remote.AppiumCommandExecutor.lambda$null$0(AppiumCommandExecutor.java:187)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
	... 14 more
Caused by: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
	at org.asynchttpclient.exception.RemotelyClosedException.INSTANCE(Unknown Source)

Process finished with exit code 1

**Comment by krishtoautomate** [comment]
no longer an issue
