### ISSUE TITLE
[Need support]: healenium connection

### ISSUE THREAD

**Issue by famartinez2024** [healenium/healenium#58]
### Describe the problem

Hello, the healenium log with selenium grid shows me the following exception, could someone help me understand it?

**Comment by famartinez2024** [comment]
2024-09-16 22:43:55.654  INFO 21044 - [       main] .e.h.h.HealeniumProxyApplication : Starting HealeniumProxyApplication v2.0.0 using Java 22.0.1 with PID 21044 (E:\heeee\healenium-2.0.0\shell-installation\selenium-grid\hlm-proxy.jar started by famartinez in E:\heeee\healenium-2.0.0\shell-installation\selenium-grid) 
2024-09-16 22:43:55.661  INFO 21044 - [       main] .e.h.h.HealeniumProxyApplication : No active profile set, falling back to 1 default profile: "default" 
2024-09-16 22:43:58.493  INFO 21044 - [       main] o.s.c.c.scope.GenericScope       : BeanFactory id=9d4f97c4-fab2-39c9-ba48-1527ca061d8d 
2024-09-16 22:44:00.996  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [After] 
2024-09-16 22:44:00.997  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Before] 
2024-09-16 22:44:00.997  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Between] 
2024-09-16 22:44:00.998  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Cookie] 
2024-09-16 22:44:00.998  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Header] 
2024-09-16 22:44:00.998  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Host] 
2024-09-16 22:44:00.998  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Method] 
2024-09-16 22:44:00.999  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Path] 
2024-09-16 22:44:00.999  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Query] 
2024-09-16 22:44:00.999  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [ReadBody] 
2024-09-16 22:44:00.999  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [RemoteAddr] 
2024-09-16 22:44:00.999  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [XForwardedRemoteAddr] 
2024-09-16 22:44:00.999  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Weight] 
2024-09-16 22:44:01.000  INFO 21044 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [CloudFoundryRouteService] 
2024-09-16 22:44:02.505  INFO 21044 - [       main] o.s.b.w.e.netty.NettyWebServer   : Netty started on port 8085 (http) 
2024-09-16 22:44:02.729  INFO 21044 - [       main] .e.h.h.HealeniumProxyApplication : Started HealeniumProxyApplication in 8.799 seconds (process running for 10.705) 
2024-09-16 22:44:06.346 ERROR 21044 - [-http-nio-2] AbstractErrorWebExceptionHandler : [b69cf2ea-1]  500 Server Error for HTTP POST "/graphql" io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: getsockopt: localhost/127.0.0.1:4444\n \n 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: \n \n Error has been observed at the following site(s):\n \n 	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]\n \n 	*__checkpoint ⇢ HTTP POST "/graphql" [ExceptionHandlingWebHandler]\n \n Original Stack Trace:\n \n Caused by: java.net.ConnectException: Connection refused: getsockopt\n \n 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)\n \n 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)\n \n 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:1060)\n \n 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336)\n \n 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)\n \n 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)\n \n 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)\n \n 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n \n 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n \n 	at java.base/java.lang.Thread.run(Thread.java:1570)\n \n 
2024-09-16 22:44:11.613 ERROR 21044 - [-http-nio-2] AbstractErrorWebExceptionHandler : [b69cf2ea-2]  500 Server Error for HTTP POST "/graphql" io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: getsockopt: localhost/127.0.0.1:4444\n \n 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: \n \n Error has been observed at the following site(s):\n \n 	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]\n \n 	*__checkpoint ⇢ HTTP POST "/graphql" [ExceptionHandlingWebHandler]\n \n Original Stack Trace:\n \n Caused by: java.net.ConnectException: Connection refused: getsockopt\n \n 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)\n \n 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)\n \n 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:1060)\n \n 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336)\n \n 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)\n \n 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)\n \n 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)\n \n 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n \n 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n \n 	at java.base/java.lang.Thread.run(Thread.java:1570)\n \n 
2024-09-16 22:44:17.612 ERROR 21044 - [-http-nio-2] AbstractErrorWebExceptionHandler : [b69cf2ea-3]  500 Server Error for HTTP POST "/graphql" io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: getsockopt: localhost/127.0.0.1:4444\n \n 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: \n \n Error has been observed at the following site(s):\n \n 	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]\n \n 	*__checkpoint ⇢ HTTP POST "/graphql" [ExceptionHandlingWebHandler]\n \n Original Stack Trace:\n \n Caused by: java.net.ConnectException: Connection refused: getsockopt\n \n 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)\n \n 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)\n \n 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:1060)\n \n 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336)\n \n 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)\n \n 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)\n \n 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)\n \n 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n \n 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n \n 	at java.base/java.lang.Thread.run(Thread.java:1570)\n \n 
2024-09-16 22:44:23.612 ERROR 21044 - [-http-nio-2] AbstractErrorWebExceptionHandler : [b69cf2ea-4]  500 Server Error for HTTP POST "/graphql" io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: getsockopt: localhost/127.0.0.1:4444\n \n 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: \n \n Error has been observed at the following site(s):\n \n 	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]\n \n 	*__checkpoint ⇢ HTTP POST "/graphql" [ExceptionHandlingWebHandler]\n \n Original Stack Trace:\n \n Caused by: java.net.ConnectException: Connection refused: getsockopt\n \n 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)\n \n 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)\n \n 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:1060)\n \n 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336)\n \n 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)\n \n 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)\n \n 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)\n \n 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n \n 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n \n 	at java.base/java.lang.Thread.run(Thread.java:1570)\n \n 
2024-09-16 22:44:29.615 ERROR 21044 - [-http-nio-2] AbstractErrorWebExceptionHandler : [b69cf2ea-5]  500 Server Error for HTTP POST "/graphql" io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: getsockopt: localhost/127.0.0.1:4444\n \n 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: \n \n Error has been observed at the following site(s):\n \n 	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]\n \n 	*__checkpoint ⇢ HTTP POST "/graphql" [ExceptionHandlingWebHandler]\n \n Original Stack Trace:\n \n Caused by: java.net.ConnectException: Connection refused: getsockopt\n \n 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)\n \n 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)\n \n 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:1060)\n \n 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336)\n \n 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)\n \n 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)\n \n 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)\n \n 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n \n 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n \n 	at java.base/java.lang.Thread.run(Thread.java:1570)\n \n 
2024-09-16 22:44:35.611 ERROR 21044 - [-http-nio-2] AbstractErrorWebExceptionHandler : [b69cf2ea-6]  500 Server Error for HTTP POST "/graphql" io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: getsockopt: localhost/127.0.0.1:4444\n \n 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: \n \n Error has been observed at the following site(s):\n \n 	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]\n \n 	*__checkpoint ⇢ HTTP POST "/graphql" [ExceptionHandlingWebHandler]\n \n Original Stack Trace:\n \n Caused by: java.net.ConnectException: Connection refused: getsockopt\n \n 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)\n \n 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)\n \n 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:1060)\n \n 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336)\n \n 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)\n \n 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)\n \n 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)\n \n 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)\n \n 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n \n 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n \n 	at java.base/java.lang.Thread.run(Thread.java:1570)\n \n 
2024-09-17 02:14:06.651  INFO 19256 - [       main] .e.h.h.HealeniumProxyApplication : Starting HealeniumProxyApplication v2.0.0 using Java 22.0.1 with PID 19256 (E:\heeee\healenium-2.0.0\shell-installation\selenium-grid\hlm-proxy.jar started by famartinez in E:\heeee\healenium-2.0.0\shell-installation\selenium-grid) 
2024-09-17 02:14:06.677  INFO 19256 - [       main] .e.h.h.HealeniumProxyApplication : No active profile set, falling back to 1 default profile: "default" 
2024-09-17 02:14:09.855  INFO 19256 - [       main] o.s.c.c.scope.GenericScope       : BeanFactory id=9d4f97c4-fab2-39c9-ba48-1527ca061d8d 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [After] 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Before] 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Between] 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Cookie] 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Header] 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Host] 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Method] 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Path] 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Query] 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [ReadBody] 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [RemoteAddr] 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [XForwardedRemoteAddr] 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Weight] 
2024-09-17 02:14:12.641  INFO 19256 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [CloudFoundryRouteService] 
2024-09-17 02:14:14.173  INFO 19256 - [       main] o.s.b.w.e.netty.NettyWebServer   : Netty started on port 8085 (http) 
2024-09-17 02:14:14.605  INFO 19256 - [       main] .e.h.h.HealeniumProxyApplication : Started HealeniumProxyApplication in 9.952 seconds (process running for 11.691) 
2024-09-17 02:15:46.101  INFO 21932 - [       main] .e.h.h.HealeniumProxyApplication : Starting HealeniumProxyApplication v2.0.0 using Java 22.0.1 with PID 21932 (E:\heeee\healenium-2.0.0\shell-installation\selenium-grid\hlm-proxy.jar started by famartinez in E:\heeee\healenium-2.0.0\shell-installation\selenium-grid) 
2024-09-17 02:15:46.107  INFO 21932 - [       main] .e.h.h.HealeniumProxyApplication : No active profile set, falling back to 1 default profile: "default" 
2024-09-17 02:15:48.702  INFO 21932 - [       main] o.s.c.c.scope.GenericScope       : BeanFactory id=9d4f97c4-fab2-39c9-ba48-1527ca061d8d 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [After] 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Before] 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Between] 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Cookie] 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Header] 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Host] 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Method] 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Path] 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Query] 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [ReadBody] 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [RemoteAddr] 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [XForwardedRemoteAddr] 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Weight] 
2024-09-17 02:15:50.858  INFO 21932 - [       main] .g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [CloudFoundryRouteService] 
2024-09-17 02:15:52.186  INFO 21932 - [       main] o.s.b.w.e.netty.NettyWebServer   : Netty started on port 8085 (http) 
2024-09-17 02:15:52.559  INFO 21932 - [       main] .e.h.h.HealeniumProxyApplication : Started HealeniumProxyApplication in 7.997 seconds (process running for 9.647)
