### ISSUE TITLE
[BUG]: Unable to run start after update healenium proxy to version 2.1.2

### ISSUE THREAD

**Issue by alavi8680** [healenium/healenium#62]
### Describe the bug

When sending commands to healenium proxy, its should forward them to correct path of appium server (which set on SELENIUM_SRVER_URL). im using this url with base_path /wd/path, but the commands from proxy going to appium server url without /wd/hub.
proxy log:
`2024-10-28 16:52:51.261  INFO 1 - [ttp-epoll-2] healenium                        : [Proxy] Using Selenium server: http://appium:4723/wd/hub 

2024-10-28 16:52:51.752 ERROR 1 - [ttp-epoll-2] AbstractErrorWebExceptionHandler : [7c4fbf7a-1]  500 Server Error for HTTP POST "/session" java.lang.IllegalArgumentException: Session ID key must be set\n 	at org.openqa.selenium.internal.Require.nonNull(Require.java:61)\n`
you can see im running the appium server on http://appium:4723/wd/hub, but the commands goes to  "/session" and not to  "wd/hub/session", and that why i get 404 error from appium server.
same test worked for me with healenium proxy 1.3.5.

### How to reproduce the issue

```shell
1.running all healenium components on docker
2. use URL of healenium proxy instead of appium server URL
3. set SELENIUM_SRVER_URL to point the appium server
4. execute the test
```

### Logs appeared during using Healenium

```shell
2024-10-28 16:52:51.261  INFO 1 - [ttp-epoll-2] healenium                        : [Proxy] Using Selenium server: http://appium:4723/wd/hub 

2024-10-28 16:52:51.752 ERROR 1 - [ttp-epoll-2] AbstractErrorWebExceptionHandler : [7c4fbf7a-1]  500 Server Error for HTTP POST "/session" java.lang.IllegalArgumentException: Session ID key must be set\n 	at org.openqa.selenium.internal.Require.nonNull(Require.java:61)\n
```

### Expected behavior

request should forward to /wd/hub/session 

### Actual behavior

request forward to /session even that appium using  base_path /wd/path

### Healenium Web version

2.1.2

### Healenium Backend version

3.4.5

### Platform

java

**Comment by Alex-Reif** [comment]
Hi @alavi8680 , We recommend to remove "/wd/path" from SELENIUM_SRVER_URL

**Comment by alavi8680** [comment]
hey, thanks for response.
im using "/wd/hub" as base path parameter to run my appium server. I'm doing it for backward compatibility, since appium 1 use it by default. thats why I'm using it on SELENIUM_SRVER_URL. there is something else i can do?

**Comment by Krafman** [comment]
@Alex-Reif is there any plan to fix this? I think something is stripping `proxy.selenium.url` of the /wd/hub even when it is explicitly configured.
