### ISSUE TITLE
[Need support]: PSQLException: The connection attempt failed

### ISSUE THREAD

**Issue by hemapreethidevaraj** [healenium/healenium#65]
### Describe the problem

I have cloned healenium repo in my local. Just did docker up , it gives The connection attempt failed. I have uninstalled and reinstalled docker-compose, docker in my machine,used different version. But it didn't work,still facing issue

### Healenium Web version

3.8

### Healenium Backend version

3.4.6

### Logs appeared during using Healenium

```shell
healenium          | 2024-11-08 12:26:01.318  INFO 1 - [       main] c.epam.healenium.Application     : Starting Application v3.4.6 using Java 22.0.2 with PID 1 (/healenium-backend.jar started by root in /) 
healenium          | 2024-11-08 12:26:01.362  INFO 1 - [       main] c.epam.healenium.Application     : No active profile set, falling back to 1 default profile: "default" 
healenium          | 2024-11-08 12:26:02.280  INFO 1 - [       main] .RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode. 
healenium          | 2024-11-08 12:26:02.447  INFO 1 - [       main] .RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 161 ms. Found 4 JPA repository interfaces. 
healenium          | 2024-11-08 12:26:03.162  INFO 1 - [       main] o.s.b.w.e.t.TomcatWebServer      : Tomcat initialized with port 7878 (http) 
healenium          | 2024-11-08 12:26:03.175  INFO 1 - [       main] o.a.c.core.StandardService       : Starting service [Tomcat] 
healenium          | 2024-11-08 12:26:03.175  INFO 1 - [       main] o.a.c.core.StandardEngine        : Starting Servlet engine: [Apache Tomcat/10.1.30] 
healenium          | 2024-11-08 12:26:03.218  INFO 1 - [       main] o.a.c.c.C.[.[localhost].[/]      : Initializing Spring embedded WebApplicationContext 
healenium          | 2024-11-08 12:26:03.218  INFO 1 - [       main] rvletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1808 ms 
healenium          | 2024-11-08 12:26:03.484  INFO 1 - [       main] c.z.hikari.HikariDataSource      : HikariPool-1 - Starting... 
healenium          | 2024-11-08 12:26:13.540 ERROR 1 - [       main] c.z.hikari.pool.HikariPool       : HikariPool-1 - Exception during pool initialization. org.postgresql.util.PSQLException: The connection attempt failed.\n 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)\n 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)\n 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)\n 	at org.postgresql.Driver.makeConnection(Driver.java:443)\n 	at org.postgresql.Driver.connect(Driver.java:297)\n 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)\n 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)\n 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)\n 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)\n 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)\n 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)\n 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)\n 	at liquibase.integration.spring.SpringLiquibase.lambda$afterPropertiesSet$0(SpringLiquibase.java:291)\n 	at liquibase.Scope.lambda$child$0(Scope.java:186)\n 	at liquibase.Scope.child(Scope.java:195)\n 	at liquibase.Scope.child(Scope.java:185)\n 	at liquibase.Scope.child(Scope.java:164)\n 	at liquibase.Scope.child(Scope.java:252)\n 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:287)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)\n 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205)\n 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:954)\n 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625)\n 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)\n 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)\n 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)\n 	at com.epam.healenium.Application.main(Application.java:9)\n 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)\n 	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:102)\n 	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64)\n 	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:40)\n Caused by: java.net.SocketTimeoutException: Connect timed out\n 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)\n 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)\n 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)\n 	at java.base/java.net.Socket.connect(Socket.java:752)\n 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)\n 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)\n 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)\n at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)\n 	... 42 common frames omitted\n 
healenium          | 2024-11-08 12:26:13.550  WARN 1 - [       main] rvletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Failed to initialize dependency 'liquibase' of LoadTimeWeaverAware bean 'entityManagerFactory': Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: The connection attempt failed. 
healenium          | 2024-11-08 12:26:13.554  INFO 1 - [       main] o.a.c.core.StandardService       : Stopping service [Tomcat] 
healenium          | 2024-11-08 12:26:13.570  INFO 1 - [       main] .ConditionEvaluationReportLogger : \n \n Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled. 
healenium          | 2024-11-08 12:26:13.587 ERROR 1 - [       main] o.s.boot.SpringApplication       : Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Failed to initialize dependency 'liquibase' of LoadTimeWeaverAware bean 'entityManagerFactory': Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: The connection attempt failed.\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:326)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205)\n 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:954)\n 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625)\n 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)\n 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)\n 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)\n 	at com.epam.healenium.Application.main(Application.java:9)\n 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)\n 	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:102)\n 	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64)\n 	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:40)\n Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: The connection attempt failed.\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1806)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)\n 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313)\n 	... 15 common frames omitted\n Caused by: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: The connection attempt failed.\n 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:304)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802)\n 	... 22 common frames omitted\n Caused by: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: The connection attempt failed.\n 	at liquibase.integration.spring.SpringLiquibase.lambda$afterPropertiesSet$0(SpringLiquibase.java:296)\n 	at liquibase.Scope.lambda$child$0(Scope.java:186)\n 	at liquibase.Scope.child(Scope.java:195)\n 	at liquibase.Scope.child(Scope.java:185)\n 	at liquibase.Scope.child(Scope.java:164)\n 	at liquibase.Scope.child(Scope.java:252)\n 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:287)\n 	... 24 common frames omitted\n Caused by: org.postgresql.util.PSQLException: The connection attempt failed.\n 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)\n at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)\n 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)\n 	at org.postgresql.Driver.makeConnection(Driver.java:443)\n 	at org.postgresql.Driver.connect(Driver.java:297)\n 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)\n 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)\n 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)\n 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)\n 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)\n 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)\n 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)\n 	at liquibase.integration.spring.SpringLiquibase.lambda$afterPropertiesSet$0(SpringLiquibase.java:291)\n 	... 30 common frames omitted\n Caused by: java.net.SocketTimeoutException: Connect timed out\n 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)\n 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)\n 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)\n 	at java.base/java.net.Socket.connect(Socket.java:752)\n 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)\n 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)\n 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)\n 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)\n 	... 42 common frames omitted\n
```

**Comment by Alex-Reif** [comment]
Hi @hemapreethidevaraj , According to your logs, your postgresql service haven't run yet. Please check postgresql service status.

**Comment by hemapreethidevaraj** [comment]
HI @Alex-Reif , There was some issue with my docker. it got resolved after OS change. But i want further help. 
Locator is saved in postgres db , but while healing getting below error .
[main] WARN healenium - Trying to heal...
[main] WARN healenium - Error during findElement:
