### ISSUE TITLE
[BUG]: Latest healenium proxy(2.1.2) and backend(3.4.6) not supporting for Appium below 1.22.3 version

### ISSUE THREAD

**Issue by Naveenhd51** [healenium/healenium#69]
### Describe the bug

Healenium proxy and backend not supporting for executing Appium 1.22.3 version, its throws error for session creation.

### How to reproduce the issue

```shell
Using latest healenium backend and proxy for version for executing appium 1.22.3 scripts.
```

### Logs appeared during using Healenium

```shell
2024-11-18 18:18:39.870  INFO 13420 - [       main] ontainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2024-11-18 18:18:40.349  INFO 13420 - [       main] o.s.d.j.r.q.QueryEnhancerFactory : Hibernate is in classpath; If applicable, HQL parser will be used.
2024-11-18 18:18:41.098  INFO 13420 - [       main] .a.w.s.WelcomePageHandlerMapping : Adding welcome page template: index
2024-11-18 18:18:41.870  INFO 13420 - [       main] .s.b.a.e.w.EndpointLinksResolver : Exposing 1 endpoint beneath base path '/actuator'
2024-11-18 18:18:42.033  INFO 13420 - [       main] o.s.b.w.e.t.TomcatWebServer      : Tomcat started on port 7878 (http) with context path '/'
2024-11-18 18:18:42.181  INFO 13420 - [       main] c.epam.healenium.Application     : Started Application in 14.277 seconds (process running for 15.943)
2024-11-18 18:20:49.454  WARN 13320 - [-http-nio-2] .InitSessionGatewayFilterFactory : Init Session: {"status":9,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":""}}




Appium logs:
[debug] [35m[HTTP][39m No route found for /session
[35m[HTTP][39m [37m<-- POST /session [39m[33m404[39m [90m11 ms - 211[39m
[35m[HTTP][39m [90m[39m
org.openqa.selenium.SessionNotCreatedException: 
Unable to create a new remote session. Desired capabilities = Capabilities {adbExecTimeout: 50000, app: C:\Users\qeuser\apps\app.apk, appWaitDuration: 30000, autoGrantPermissions: true, avd: Android_Emulator_1, avdLaunchTimeout: 120000, commandTimeout: 600, idleTimeout: 1000, maxDuration: 900, newCommandTimeout: 600, noReset: false, platformName: android, platformVersion: 14.0}
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.lambda$1(AppiumCommandExecutor.java:201)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:201)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:225)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:99)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:97)
	at com.ipc.core.SingleDriverTestCore.initAppiumDriver(SingleDriverTestCore.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Expected behavior

It should be work or supported

### Actual behavior

it's not working and supporting

### Healenium Web version

3.4.6

### Healenium Backend version

3.4.6

### Selenium version

3 and Appium 1.22.3

### Platform

Java

**Comment by Alex-Reif** [comment]
Hi @Naveenhd51 , please check with actual healenium version 2.1.8
